name: live

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

  schedule:
    - cron: "23 23 * * *"

jobs:
  live:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependecies
        run: |
          sudo apt update
          sudo apt install -y \
          build-essential \
          cmake \
          libgtest-dev \
          libgmock-dev \
          libcurl4-openssl-dev \
          libasio-dev \
          libxml2-dev
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build --parallel
      - name: Run live tests
        run: ctest --test-dir build --output-on-failure -L live
